checkpoint:
  path: /home/aquinoarjay/thesis/SpecRNet/trained_models/model__specrnet__1727459249.4610372/ckpt.pth
data:
  seed: 42
model:
  name: specrnet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    frontend_algorithm:
    - lfcc
    input_channels: 1
